from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Callable

from autogen_mas.models import AnswerSubmission, PriorRoundFeedback, TaskRecord

if TYPE_CHECKING:
    from autogen_mas.runtime.adversarial.strategy import AnswerPlan, ReviewPlan
else:
    AnswerPlan = object
    ReviewPlan = object


AnswerPromptBuilder = Callable[
    [TaskRecord, AnswerPlan, int, PriorRoundFeedback | None, bool],
    str,
]
ReviewPromptBuilder = Callable[
    [TaskRecord, int, AnswerSubmission, AnswerSubmission, ReviewPlan, bool],
    str,
]


@dataclass(frozen=True, slots=True)
class ChoiceBaselineSpec:
    strategy_name: str
    aliases: tuple[str, ...]
    default_answer_system_prompt: str
    default_review_system_prompt: str
    reasoning_bank_enabled: bool
    review_candidate_reranker_enabled: bool
    build_answer_prompt: AnswerPromptBuilder
    build_review_prompt: ReviewPromptBuilder
    use_provider_default_temperature: bool = False
    review_model_scores_enabled: bool = False
    # When True, the choice review rationale is generated by retrieving from the
    # reasoning-bank corpus, producing several candidate rationales, and randomly
    # selecting one of them. The controller-assigned score/stance/target are left
    # untouched (only the rationale text changes).
    reasoning_bank_review_enabled: bool = False
    reasoning_bank_review_candidate_count: int = 3
