from .spec import (
    BASELINE_1_TEST_2_ALIASES,
    BASELINE_1_TEST_2_ANSWER_SYSTEM_PROMPT,
    BASELINE_1_TEST_2_REVIEW_SYSTEM_PROMPT,
    BASELINE_1_TEST_2_SPEC,
    BASELINE_1_TEST_2_STRATEGY_NAME,
)

__all__ = [
    "BASELINE_1_TEST_2_ALIASES",
    "BASELINE_1_TEST_2_ANSWER_SYSTEM_PROMPT",
    "BASELINE_1_TEST_2_REVIEW_SYSTEM_PROMPT",
    "BASELINE_1_TEST_2_SPEC",
    "BASELINE_1_TEST_2_STRATEGY_NAME",
]
