from .spec import (
    BASELINE_1_ALIASES,
    BASELINE_1_ANSWER_SYSTEM_PROMPT,
    BASELINE_1_REVIEW_SYSTEM_PROMPT,
    BASELINE_1_SPEC,
    BASELINE_1_STRATEGY_NAME,
)

__all__ = [
    "BASELINE_1_ALIASES",
    "BASELINE_1_ANSWER_SYSTEM_PROMPT",
    "BASELINE_1_REVIEW_SYSTEM_PROMPT",
    "BASELINE_1_SPEC",
    "BASELINE_1_STRATEGY_NAME",
]
